id: I567CB871
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:49:45+00:00'
last_modified: '2022-06-08T06:37:18.307935+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9087
  title: ཚངས་དབྱངས་རྒྱ་མཚོའི་རྣམ་ཐར། ༼ལྷ་ས་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    45D3:
      image_group_id: I1KG9109
      title: ''
      total_pages: 607
      order: 1
      base_file: 45D3.txt
    FB18:
      image_group_id: I1KG9110
      title: ''
      total_pages: 431
      order: 2
      base_file: FB18.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
