id: I567CB871
legacy_id: P006754
ocr_import_info:
  bdrc_scan_id: W1KG9087
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T09:48:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:17:54.372875+00:00'
last_modified: 2022-09-01 02:18:20.190002
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9087
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9087
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚངས་དབྱངས་རྒྱ་མཚོའི་རྣམ་ཐར། ༼དགའ་ལྡན་ཕོ་བྲང། ལྷ་ས་པར་མ།༽
  author: སྡེ་སྲིད་སངས་རྒྱས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7151049126876974
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I1KG9110:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9110
      total_pages: 431
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG9110.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6954380786486682
    legacy_id: v002
  I1KG9109:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9109
      total_pages: 607
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9109.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7300445668459683
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
