id: P006754
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG9087
  title: ཚངས་དབྱངས་རྒྱ་མཚོའི་རྣམ་ཐར། ༼ལྷ་ས་པར་མ།༽
  author: ''
  volumes:
    e0f66961700d426a99913369216a790f:
      image_group_id: I1KG9109
      title: ''
      volume_number: 1
      total_pages: 607
      base_file: v001.txt
    06f6cc8713de46299eedf851f7be11bc:
      image_group_id: I1KG9110
      title: ''
      volume_number: 2
      total_pages: 431
      base_file: v002.txt
